export * from "./types";

// Fintech & Core Banking Icons
export {
  ShieldCheckIcon,
  ShieldCheckIcon as ShieldCheck,
  SparklesIcon,
  SparklesIcon as Sparkles,
  CpuIcon,
  CpuIcon as Cpu,
  UsersIcon,
  UsersIcon as Users,
  SmartphoneIcon,
  SmartphoneIcon as Smartphone,
  RepeatIcon,
  RepeatIcon as Repeat,
  TrendingUpIcon,
  TrendingUpIcon as TrendingUp,
  ShoppingBagIcon,
  ShoppingBagIcon as ShoppingBag,
  HandshakeIcon,
  HandshakeIcon as Handshake,
  AwardIcon,
  AwardIcon as Award,
  ActivityIcon,
  ActivityIcon as Activity,
  ZapIcon,
  ZapIcon as Zap,
  ClockIcon,
  ClockIcon as Clock,
  ReceiptIcon,
  ReceiptIcon as Receipt,
  ArrowLeftRightIcon,
  ArrowLeftRightIcon as ArrowLeftRight,
  QrCodeIcon,
  QrCodeIcon as QrCode,
  SendIcon,
  SendIcon as Send,
  PlusCircleIcon,
  PlusCircleIcon as PlusCircle,
  BuildingIcon,
  BuildingIcon as Building,
  CheckCircle2Icon,
  CheckCircle2Icon as CheckCircle2,
} from "./FintechIcons";

// Navigation, Directional & UI Icons
export {
  ArrowUpRightIcon,
  ArrowUpRightIcon as ArrowUpRight,
  ArrowUpLeftIcon,
  ArrowUpLeftIcon as ArrowUpLeft,
  ArrowLeftIcon,
  ArrowLeftIcon as ArrowLeft,
  ArrowUpIcon,
  ArrowUpIcon as ArrowUp,
  ArrowDownToLineIcon,
  ArrowDownToLineIcon as ArrowDownToLine,
  ChevronLeftIcon,
  ChevronLeftIcon as ChevronLeft,
  MenuIcon,
  MenuIcon as Menu,
  XIcon,
  XIcon as X,
  HomeIcon,
  HomeIcon as Home,
  UserIcon,
  UserIcon as User,
  BellIcon,
  BellIcon as Bell,
} from "./NavigationIcons";

// Contact, Communication & Vision Icons
export {
  PhoneIcon,
  PhoneIcon as Phone,
  MessageSquareIcon,
  MessageSquareIcon as MessageSquare,
  MailIcon,
  MailIcon as Mail,
  MapPinIcon,
  MapPinIcon as MapPin,
  CompassIcon,
  CompassIcon as Compass,
  TargetIcon,
  TargetIcon as Target,
} from "./ContactIcons";

// Store & Platform Icons
export {
  AppleIcon,
  GooglePlayIcon,
  AndroidIcon,
} from "./StoreIcons";
